version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: aria
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: aria_db
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aria"]
      interval: 5s
      retries: 10

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: verify_db
      MYSQL_USER: verifier
      MYSQL_PASSWORD: changeme
    ports:
      - "33306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  keydb:
    image: eqalpha/keydb
    ports:
      - "16380:6379"
    command: --server-threads 2
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      retries: 10

  memcached:
    image: memcached:1.6
    ports:
      - "11212:11211"
    healthcheck:
      test: ["CMD", "echo", "stats", "|", "nc", "localhost", "11211"]
      interval: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "56720:5672"      # AMQP
      - "15673:15672"     # Management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 10
